before_script:
  - cd ./server

include:
  - local: '/server/.gitlab-ci.yml'

image: node:8.10.0

cache:
  paths:
    - node_modules/

stages:
  - install
  - deploy_production

# Job 1:
install:
  only:
    - staging  # to change to main
  stage: install
  script:
    - npm install

# Job 2:
# Deploy to staging
Production:
  image: ruby:latest
  only:
    - staging     # to change to main
  stage: deploy_production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
