export enum SOCKETEVENT {
   JOINROOM="JOINROOM",
   CREATEROOM="CREATEROOM",
   MESSAGE="MSG",
   DISCONNECT="DISCONNECT",
   ROOMDELETED="ROOMDELETED",
   DRAWINGCREATED="DRAWINGCREATED",
   UNOTCONNECTED="user is not connected",
   JOINDRAWING="JOINDRAWING",
   DRAWINGDELETED="DRAWINGDELETED",
   ALBUMCREATED="ALBUMCREATED",
   LEAVEROOM="LEAVEROOM"
}
